import Link from "next/link";
import { LearnerShell } from "@/components/learner-shell";
import { isInstructor, displayName, isAdmin, requireUser, userRecords, visibleLessons } from "@/lib/learning-server";

export default async function Progress() {
  const user = await requireUser();
  const [name, records, lessons] = await Promise.all([displayName(user), userRecords(user), visibleLessons(user)]);
  const average = records.attempts.length ? Math.round(records.attempts.reduce((total, attempt) => total + attempt.score * 10, 0) / records.attempts.length) : null;
  const passedCount = new Set(records.attempts.filter(attempt => attempt.score >= 6).map(attempt => attempt.original_lesson_id)).size;
  return <LearnerShell active="/progress" name={name} admin={isAdmin(user)} instructor={isInstructor(user)}><div className="portal-page"><span className="eyebrow">YOUR PROGRESS</span><h1>Your learning record.</h1><section className="stat-grid"><div><strong>{records.enrollments.filter(record => record.attended_at).length}</strong><span>Lessons attended</span></div><div><strong>{passedCount}</strong><span>Lessons passed</span></div><div><strong>{average === null ? "Not yet" : `${average}%`}</strong><span>Average across attempts</span></div><div><strong>{records.bookmarks.length}</strong><span>Saved lessons</span></div></section><section className="learning-section"><h2>Quiz history</h2>{!records.attempts.length && <p>No quiz attempts yet.</p>}{records.attempts.map(attempt => <div className="result-row" key={attempt.id}><span><strong>{attempt.lesson_title}</strong><small>{attempt.certificate_kind === "private" ? "Private Self-Learning" : "Public Published Lesson"} · Version {attempt.lesson_version} · {new Date(attempt.completed_at).toLocaleDateString("en-GB", { timeZone: "UTC" })}</small></span><b>{attempt.score}/10</b>{attempt.score >= 6 && <a className="text-link" href={`/api/certificates/${attempt.id}`}>Certificate (HTML)</a>}</div>)}</section><section className="learning-section"><h2>Saved lessons</h2>{lessons.filter(lesson => records.bookmarks.some(bookmark => bookmark.lesson_id === lesson.id)).map(lesson => <p key={lesson.id}><Link href={`/courses/${lesson.id}`} className="text-link">{lesson.title}</Link></p>)}{!records.bookmarks.length && <p>No saved lessons yet.</p>}</section></div></LearnerShell>;
}