import Image from "next/image";
import Link from "next/link";
import { Search } from "lucide-react";
import { LearnerShell } from "@/components/learner-shell";
import { displayName, isAdmin, requireUser, userRecords, visibleLessons } from "@/lib/learning-server";

export default async function Catalog({ searchParams }: { searchParams: Promise<{ q?: string; subject?: string; visibility?: string }> }) {
  const user = await requireUser();
  const [name, lessons, records, rawFilters] = await Promise.all([displayName(user), visibleLessons(user), userRecords(user), searchParams]);
  const filters = { q: typeof rawFilters.q === "string" ? rawFilters.q : "", subject: typeof rawFilters.subject === "string" ? rawFilters.subject : "", visibility: typeof rawFilters.visibility === "string" ? rawFilters.visibility : "" };
  const query = (filters.q ?? "").toLowerCase();
  const matches = lessons.filter(lesson => `${lesson.title} ${lesson.summary} ${lesson.subject}`.toLowerCase().includes(query) && (!filters.subject || lesson.subject === filters.subject) && (!filters.visibility || lesson.visibility === filters.visibility));
  return <LearnerShell active="/catalog" name={name} admin={isAdmin(user)}><div className="portal-page"><header className="portal-heading"><div><span className="eyebrow">LESSON CATALOG</span><h1>Find your next useful skill.</h1></div><Link className="secondary-button" href="/studio">Create a private lesson</Link></header><form className="catalog-filters" action="/catalog"><label>Search<input name="q" defaultValue={filters.q} maxLength={150} placeholder="Topic or lesson" /></label><label>Subject<select name="subject" defaultValue={filters.subject ?? ""}><option value="">All subjects</option>{Array.from(new Set(lessons.map(lesson => lesson.subject))).map(subject => <option key={subject}>{subject}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={filters.visibility ?? ""}><option value="">All available</option><option value="public">Public published</option><option value="private">My private lessons</option></select></label><button className="auth-submit"><Search size={17} />Search</button><Link href="/catalog">Clear</Link></form><section className="catalog-grid">{matches.map(lesson => <article className="catalog-card" key={lesson.id}><div className="catalog-image"><Image src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80" alt="" fill sizes="(max-width: 700px) 100vw, 33vw" /><span>{lesson.visibility === "private" ? "PRIVATE" : "PUBLISHED"}</span></div><div className="catalog-copy"><small>{lesson.subject}</small><h2>{lesson.title}</h2><p>{lesson.summary}</p><Link href={`/courses/${lesson.id}`}>{records.enrollments.some(record => record.lesson_id === lesson.id) ? "Continue lesson" : "View and enroll"}</Link></div></article>)}</section>{matches.length === 0 && <div className="empty-state"><h2>No matching lessons.</h2><Link href="/studio" className="text-link">Generate your own topic</Link></div>}</div></LearnerShell>;
}